version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: elo_system
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    restart: always
    ports:
      - "8081:80"

volumes:
  db_data:
